# Generated by Django 5.0.6 on 2024-08-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miaplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deportivo',
            name='imagen',
            field=models.ImageField(default='imagen', upload_to='imagenes/'),
        ),
    ]
